name: create batch tx

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Create batched tx on safe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get added script files
        id: changed-script-files
        uses: tj-actions/changed-files@v43
        with:
          files: script/**

      - name: Install Foundry
        if: steps.changed-script-files.outputs.all_changed_files == 'true'
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run script
        if: steps.changed-script-files.outputs.all_changed_files == 'true'
        env:
          SCRIPT_FILES: ${{ steps.changed-script-files.outputs.all_changed_files }}
        run: |
          if [ "$SCRIPT_FILES" = "[]" ]; then
            echo "No adapter files were modified"
            exit 0
          fi

          for i in $(echo $SCRIPT_FILES | tr  -d '"[]' | tr "," "\n")
          do
            {
              forge script ${i} --skip-simulation --chain-id 81457 --ffi -vvvvv --private-key ${{ secrets.PRIVATE_KEY }}
            }
          done
