name: create batch tx

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Create batched tx on safe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get added script files
        id: changed-script-files
        uses: tj-actions/changed-files@v43
        with:
          files: script/**

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-script-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Install Foundry
        if: steps.changed-script-files.outputs.any_changed == 'true'
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run script
        if: steps.changed-script-files.outputs.any_changed == 'true'
        env:
          WALLET_TYPE: local
          SCRIPT_FILES: ${{ steps.changed-script-files.outputs.all_changed_files }}
        run: |
          for file in ${SCRIPT_FILES}; do
            forge script $file --skip-simulation --chain-id 81457 --ffi -vvvvv --private-key ${{ secrets.PRIVATE_KEY }}
          done
