name: create batch tx

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Create batched tx on safe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get added script files
        id: changed-script-files
        uses: tj-actions/changed-files@v43
        with:
          files: script/*.sol

      - name: List all added script files
        env:
          ADDED_FILES: ${{ steps.changed-script-files.outputs.added_files }}
        run: |
          for file in ${ADDED_FILES}; do
            echo "$file was added"
          done

      - name: Install Foundry
        if: steps.changed-script-files.outputs.added_files != ''
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install libraries
        if: steps.changed-script-files.outputs.added_files != ''
        run: forge install

      - name: Run script
        if: steps.changed-script-files.outputs.added_files != ''
        env:
          WALLET_TYPE: local
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETH_RPC_URL: ${{ vars.ETH_RPC_URL }}
          SCRIPT_FILES: ${{ steps.changed-script-files.outputs.added_files }}
          SEND: true
        run: |
          for file in ${SCRIPT_FILES}; do
            forge script $file --sig 'run(bool)' $SEND --skip-simulation --ffi -vvvvv --rpc-url $ETH_RPC_URL --private-key $PRIVATE_KEY
          done
