name: create batch tx

on:
  push:
    branches:
      - main

jobs:      
  run:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files_yaml: |
            script:
              - 'script/**.s.sol'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: |
          SCRIPT_FILES = ${{ steps.changed-files.outputs.added_files }}

          for i in $(echo $RUN_FILES | tr  -d '"[]' | tr "," "\n")
          do
            {
              forge script ${i} --skip-simulation --chain-id 81457 --ffi -vvvvv --private-key ${{ secrets.PRIVATE_KEY }}
            }
          done
